### ISSUE TITLE
关于script/keyphrase_extract.py运行的问题

### ISSUE THREAD

**Issue by 1180301012** [muguruzawang/KGSum#1]
你好！我想复现一下你们的工作，但是当我运行script/keyphrase_extract.py时发现有些模块无法导入，且他们不是一个python模块，我想问一下：
```python
from  Clustering_experiment import get_entities, get_entity_index,get_entity_embedding
import Scibert_for_Clustering
```
其中的模块Clustering_experiment 以及 Scibert_for_Clustering来自于哪里呢?

**Comment by muguruzawang** [comment]
你好，我重新更新了代码和说明文档，请重新下载
