### ISSUE TITLE
关于createEntRelVocab.py运行问题

### ISSUE THREAD

**Issue by Jack11486** [muguruzawang/KGSum#2]
你好，我在复现论文代码过程中，发现createEntRelVocab.py几个存在一些问题， if ent1 in self.raw_ent_text and ent2 in self.raw_ent_text:，combs = list(combinations(cluster,2))，请问能否请帮忙解答一下。
![image](https://user-images.githubusercontent.com/127724341/224633537-e9e9dd76-ad72-4df3-ab63-964841de3551.png)

**Comment by muguruzawang** [comment]
Sorry for this error. Actually, entityvocab is not required for our model. So I update the code of train.py, module/utlis_dataloader.py and module/opts.py.  Please update the latest code to run.
