### ISSUE TITLE
关于train.label.jsonl文件内容的问题

### ISSUE THREAD

**Issue by jinxingnan** [muguruzawang/KGSum#3]
请问train.label.jsonl中“label”关键字的值是如何获取的，为何意义？如果方便的话，是否可提供您在实验中所使用的数据集。谢谢！

**Comment by muguruzawang** [comment]
label是之前用作抽取式摘要的oracle label，在本实验中没有用到。可以在module/utlis_dataloader.py中注释掉

**Comment by muguruzawang** [comment]
> 

label是之前用作抽取式摘要的oracle label，在本实验中没有用到。可以在module/utlis_dataloader.py中注释掉

**Comment by jinxingnan** [comment]
好的，谢谢您。请问模型的生成目标即文中提到的gold summary，是源自multi_xscience数据集中的abstract还是related_work字段？

**Comment by muguruzawang** [comment]
> 
是related_work字段，         abstract字段是target_paper的abstract section
